In [1]:
import numpy as np
from scipy.io import loadmat
from pathlib import Path

scratches_dir = Path("scratches")

In [2]:
data = loadmat(scratches_dir / "Signal.mat", matlab_compatible=True)
signal = data["Signal"].flatten()

In [3]:
np.fft.fft(signal)[:, np.newaxis]

array([[-0.17534951+0.j        ],
       [-0.28121498+0.14163607j],
       [ 0.21801846-0.1191667j ],
       [-0.03153431-0.12657415j],
       [-0.05781928+0.07150411j],
       [-0.15665693-0.05802842j],
       [-0.19260481+0.01129389j],
       [ 0.05428805+0.0564366j ],
       [-0.00863817-0.06482095j],
       [ 0.09579443-0.13073015j],
       [-0.0652899 -0.09488527j],
       [-0.0652899 +0.09488527j],
       [ 0.09579443+0.13073015j],
       [-0.00863817+0.06482095j],
       [ 0.05428805-0.0564366j ],
       [-0.19260481-0.01129389j],
       [-0.15665693+0.05802842j],
       [-0.05781928-0.07150411j],
       [-0.03153431+0.12657415j],
       [ 0.21801846+0.1191667j ],
       [-0.28121498-0.14163607j]])

In [4]:
np.fft.fft(signal[None, :], axis=1)

array([[-0.17534951+0.j        , -0.28121498+0.14163607j,
         0.21801846-0.1191667j , -0.03153431-0.12657415j,
        -0.05781928+0.07150411j, -0.15665693-0.05802842j,
        -0.19260481+0.01129389j,  0.05428805+0.0564366j ,
        -0.00863817-0.06482095j,  0.09579443-0.13073015j,
        -0.0652899 -0.09488527j, -0.0652899 +0.09488527j,
         0.09579443+0.13073015j, -0.00863817+0.06482095j,
         0.05428805-0.0564366j , -0.19260481-0.01129389j,
        -0.15665693+0.05802842j, -0.05781928-0.07150411j,
        -0.03153431+0.12657415j,  0.21801846+0.1191667j ,
        -0.28121498-0.14163607j]])

In [5]:
values1 = np.vstack([signal, 2*signal, signal])
values2 = np.vstack([2*signal, signal, 2*signal])

all_values = np.dstack([values1, values2, values1])

all_values[:, 0, :]

array([[-0.04888878, -0.09777756, -0.04888878],
       [-0.09777756, -0.04888878, -0.09777756],
       [-0.04888878, -0.09777756, -0.04888878]])

In [6]:
ff = np.fft.fft(all_values, axis=1)
ff.shape

(3, 21, 3)

In [7]:
ff[:, 1, :]

array([[-0.28121498+0.14163607j, -0.56242996+0.28327214j,
        -0.28121498+0.14163607j],
       [-0.56242996+0.28327214j, -0.28121498+0.14163607j,
        -0.56242996+0.28327214j],
       [-0.28121498+0.14163607j, -0.56242996+0.28327214j,
        -0.28121498+0.14163607j]])

In [8]:
ff.shape

(3, 21, 3)

In [9]:
(all_values[0, :, 0] == all_values[0, :, 2]).all(), (ff[0, :, 0] == ff[0, :, 2]).all()

(True, True)

In [10]:
np.absolute(ff[0, :])

array([[0.17534951, 0.35069902, 0.17534951],
       [0.31486924, 0.62973849, 0.31486924],
       [0.24846076, 0.49692153, 0.24846076],
       [0.1304432 , 0.2608864 , 0.1304432 ],
       [0.09195601, 0.18391202, 0.09195601],
       [0.16705895, 0.3341179 , 0.16705895],
       [0.19293565, 0.38587131, 0.19293565],
       [0.07830889, 0.15661778, 0.07830889],
       [0.06539398, 0.13078797, 0.06539398],
       [0.1620708 , 0.32414161, 0.1620708 ],
       [0.11517806, 0.23035611, 0.11517806],
       [0.11517806, 0.23035611, 0.11517806],
       [0.1620708 , 0.32414161, 0.1620708 ],
       [0.06539398, 0.13078797, 0.06539398],
       [0.07830889, 0.15661778, 0.07830889],
       [0.19293565, 0.38587131, 0.19293565],
       [0.16705895, 0.3341179 , 0.16705895],
       [0.09195601, 0.18391202, 0.09195601],
       [0.1304432 , 0.2608864 , 0.1304432 ],
       [0.24846076, 0.49692153, 0.24846076],
       [0.31486924, 0.62973849, 0.31486924]])

In [11]:
from utils.frequency import DFT

sig = np.array(
    [
        -0.0489,
        -0.0055,
        0.0077,
        0.0032,
        -0.0942,
        -0.0172,
        -0.0514,
        -0.0408,
        -0.0165,
        0.0610,
        0.0313,
        0.0292,
        0.0406,
        0.0050,
        0.0280,
        0.0202,
        -0.0176,
        -0.0371,
        -0.0469,
        0.0127,
        -0.0380,
    ]
)



In [12]:
sig

array([-0.0489, -0.0055,  0.0077,  0.0032, -0.0942, -0.0172, -0.0514,
       -0.0408, -0.0165,  0.061 ,  0.0313,  0.0292,  0.0406,  0.005 ,
        0.028 ,  0.0202, -0.0176, -0.0371, -0.0469,  0.0127, -0.038 ])