In [1]:
from pathlib import Path
import json
import numpy as np
import scipy.io as scio

scratches_dir = Path("scratches")

In [2]:
with open(scratches_dir / "foldIdx.json", "r") as f:
    kfold_py = json.load(f)

In [3]:
kfold_mat = scio.loadmat(scratches_dir / "foldIndex.mat", matlab_compatible=True)

In [4]:
folds_mat = kfold_mat["foldIdx"].flatten()
folds_py = kfold_py["folds"]

In [5]:
for Kidx, (py_kfold, mat_kfold) in enumerate(zip(folds_py, folds_mat)):
    np_fold = np.array(py_kfold)
    mat_fold = mat_kfold.flatten().astype(int) - 1

    print(Kidx, mat_fold.shape, np_fold.shape)
    print(mat_fold[:5], np_fold[:5])
    # print((mat_fold[:5]== np_fold[:5]).all())

0 (125,) (124,)
[0 1 2 3 4] [1 2 3 4 5]
1 (124,) (125,)
[0 1 2 4 5] [0 1 2 5 6]
2 (125,) (125,)
[1 2 3 5 6] [0 1 3 4 5]
3 (125,) (125,)
[0 1 3 4 6] [0 2 3 4 6]
4 (125,) (125,)
[0 2 3 4 5] [0 1 2 3 4]


In [23]:
labels = np.tile(np.arange(3), 10)
labels

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2])

In [42]:
from sklearn.model_selection import StratifiedKFold
from numpy.random import RandomState

rng = RandomState(21)
skf = StratifiedKFold(n_splits=3, random_state=rng, shuffle=True)
# skf = StratifiedKFold(n_splits=3)

for K_idx, (Kfold_train, Kfold_test) in enumerate(skf.split(np.zeros(labels.size), labels)):
    print(K_idx, Kfold_train.shape)
    print(Kfold_train+1)

0 (20,)
[ 2  7  9 11 12 13 14 15 16 17 18 20 21 22 23 24 25 26 27 28]
1 (20,)
[ 1  3  4  5  6  7  8  9 10 11 14 15 19 21 24 25 26 28 29 30]
2 (20,)
[ 1  2  3  4  5  6  8 10 12 13 16 17 18 19 20 22 23 27 29 30]


In [39]:
import numpy as np
np.random.seed(21)

skf = StratifiedKFold(n_splits=3, random_state=21, shuffle=True)
# skf = StratifiedKFold(n_splits=3)

for K_idx, (Kfold_train, Kfold_test) in enumerate(skf.split(np.zeros(labels.size), labels)):
    print(K_idx, Kfold_train.shape)
    print(Kfold_train+1)

0 (20,)
[ 2  7  9 11 12 13 14 15 16 17 18 20 21 22 23 24 25 26 27 28]
1 (20,)
[ 1  3  4  5  6  7  8  9 10 11 14 15 19 21 24 25 26 28 29 30]
2 (20,)
[ 1  2  3  4  5  6  8 10 12 13 16 17 18 19 20 22 23 27 29 30]


In [40]:
rng = RandomState(21)
rng.random((3,5)).T

array([[0.04872488, 0.05077326, 0.06957095],
       [0.28910966, 0.30227189, 0.86740448],
       [0.72096635, 0.66391029, 0.13324052],
       [0.02161625, 0.30811439, 0.17812466],
       [0.20592277, 0.58359128, 0.49592955]])

In [11]:
import numpy as np
np.random.seed(21)
np.random.random((5,3)).T


array([[0.04872488, 0.02161625, 0.30227189, 0.58359128, 0.13324052],
       [0.28910966, 0.20592277, 0.66391029, 0.06957095, 0.17812466],
       [0.72096635, 0.05077326, 0.30811439, 0.86740448, 0.49592955]])