In [1]:
import scipy.io as scio
import scipy.stats as scst
import numpy as np

np.set_printoptions(suppress=True)

In [2]:
data = scio.loadmat("XTrain.mat", matlab_compatible=True)

In [3]:
XTrain = data["a_variable"]

In [4]:
XTrain.shape

(75, 6)

In [5]:
np.mean(XTrain, axis=0)

array([ 0.00692543,  0.01303444, -0.01125017,  0.07241727,  0.31049128,
        9.76058081])

In [6]:
np.std(XTrain, axis=0)

array([0.045994  , 0.05807816, 0.04002686, 0.73714231, 0.27976866,
       0.59806351])

In [7]:
scst.skew(XTrain, axis=0)

array([ 0.1392643 , -0.15758205, -0.33952578,  0.20622694,  0.31311679,
        0.19600344])

In [9]:
scst.kurtosis(XTrain, axis=0, fisher=False)

array([2.6575473 , 2.67510436, 3.35434431, 2.1692966 , 2.45044799,
       3.24876395])